
classDiagram

  class anndataR {
    AnnData()
    read_h5ad(path, backend)
    as_AnnData(obj)
  }

  class InMemoryAnnData {
    init(X, obs, var, shape, ...)
  }

  class HDF5AnnData {
    init(h5file)
  }

  class ZarrAnnData["ZarrAnnData (Planned)"] {
    init(zarrFile)
  }
  class ReticulateAnnData["ReticulateAnnData (Planned)"] {
    init(ptr)
  }

  anndataR --> InMemoryAnnData
  anndataR --> HDF5AnnData
  anndataR --> ZarrAnnData
  anndataR --> ReticulateAnnData

  HDF5AnnData --|> AbstractAnnData
  InMemoryAnnData --|> AbstractAnnData
  ZarrAnnData --|> AbstractAnnData
  ReticulateAnnData --|> AbstractAnnData
  SubsetAnnData --|> AbstractAnnData

  

  class AbstractAnnData {
    *X: Matrix | SparseMatrix
    *layers: List[Matrix | SparseMatrix]
    *obs: DataFrame
    *var: DataFrame
    *obsp: List[Matrix | SparseMatrix | DataFrame]
    *varp: List[Matrix | SparseMatrix | DataFrame]
    *obsm: List[Matrix | SparseMatrix | DataFrame]
    *varm: List[Matrix | SparseMatrix | DataFrame]
    *uns: List
    *n_obs: int
    *n_vars: int
    *obs_names: Array[String]
    *var_names: Array[String]
    *write_h5ad(): Unit

    subset(): SubsetAnnData
    as_SingleCellExperiment(): SingleCellExperiment
    as_Seurat(): Seurat

    as_HDF5AnnData(): HDF5AnnData
    as_InMemoryAnnData(): InMemoryAnnData
  }

  AbstractAnnData --> SingleCellExperiment
  AbstractAnnData --> Seurat
  AbstractAnnData --> SubsetAnnData

  class SubsetAnnData {
    init(ad)
  }
