on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

name: R-CMD-check-bioc

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

jobs:
  R-CMD-check-bioc:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.bioc-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, bioc-version: 'devel', bioc-mirror: 'https://bioconductor.posit.co/',  Ncpus: 2}
        - { os: macOS-latest,   bioc-version: 'devel', bioc-mirror: 'https://bioconductor.posit.co/',  Ncpus: 3}
        - { os: macOS-15-intel, bioc-version: 'devel', bioc-mirror: 'https://bioconductor.posit.co/',  Ncpus: 3}
        - { os: ubuntu-latest,  bioc-version: 'devel', bioc-mirror: 'https://bioconductor.posit.co/',  Ncpus: 4}
        - { os: ubuntu-latest,  bioc-version: 'release',  bioc-mirror: 'https://packagemanager.posit.co/bioconductor',  Ncpus: 4}
    steps:

      ## R CMD check complains about Windows line endings without this
      - name: Configure git
        run: |
          git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Set paths
        id: set-paths
        run: |
          echo "pkg-name=$(echo ${PWD##*/})" >> $GITHUB_OUTPUT
          echo "pkg-dir=$(echo ${PWD##*/})" >> $GITHUB_OUTPUT
          echo "working-dir=$(echo '../')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Show paths
        run: |
          echo "Package name: ${{ steps.set-paths.outputs.pkg-name }}"
          echo "Package dir: ${{ steps.set-paths.outputs.pkg-dir }}"
          echo "Working dir: ${{ steps.set-paths.outputs.working-dir }}"
        shell: bash

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -y install hdf5-tools

      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc-version }}
          bioc-mirror: ${{ matrix.config.bioc-mirror }}

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Bioc - Build, Install, Check
        uses: grimbough/bioc-actions/build-install-check@v1
        
      - name: Show testthat output
        run: |
          ## --------------------------------------------------------------------
          echo ::group::Show testthat output
          find . -name 'testthat.Rout*' -exec cat '{}' \; || true
          echo ::endgroup::
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('{0}-{1}-r{2}-{3}-results', runner.os, runner.arch, matrix.config.bioc-version, matrix.config.id ) }}
          path: ${{ steps.set-paths.outputs.pkg-dir }}

      - name: Run BiocCheck
        if: matrix.config.os == 'ubuntu-latest' && matrix.config.bioc-version == 'devel'
        uses: grimbough/bioc-actions/run-BiocCheck@v1
        with:
          error-on: 'never'
          arguments: '--no-check-bioc-help'
